/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbandonosTab: typeof import('./src/components/gestor/tempo-real/AbandonosTab.vue')['default']
    AppIcon: typeof import('./src/components/ui/AppIcon.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/layout/AppTopbar.vue')['default']
    AtendimentosTab: typeof import('./src/components/gestor/tempo-real/AtendimentosTab.vue')['default']
    BarList: typeof import('./src/components/gestor/BarList.vue')['default']
    BrandLogo: typeof import('./src/components/layout/BrandLogo.vue')['default']
    ChartCard: typeof import('./src/components/gestor/ChartCard.vue')['default']
    ColumnManager: typeof import('./src/components/ui/ColumnManager.vue')['default']
    ConfigurarColunas: typeof import('./src/components/ocorrencias/ConfigurarColunas.vue')['default']
    CopilotButton: typeof import('./src/components/ocorrencias/CopilotButton.vue')['default']
    DataList: typeof import('./src/components/ui/DataList.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    EquipeTab: typeof import('./src/components/gestor/tempo-real/EquipeTab.vue')['default']
    FilaFab: typeof import('./src/components/fila/FilaFab.vue')['default']
    FilaPanel: typeof import('./src/components/fila/FilaPanel.vue')['default']
    FilasTab: typeof import('./src/components/gestor/tempo-real/FilasTab.vue')['default']
    FiltrosAvancados: typeof import('./src/components/ocorrencias/FiltrosAvancados.vue')['default']
    FloatingActions: typeof import('./src/components/ocorrencias/FloatingActions.vue')['default']
    FloatingDock: typeof import('./src/components/ocorrencias/FloatingDock.vue')['default']
    InicioTab: typeof import('./src/components/gestor/tempo-real/InicioTab.vue')['default']
    KanbanBoard: typeof import('./src/components/ui/KanbanBoard.vue')['default']
    MetricCard: typeof import('./src/components/gestor/MetricCard.vue')['default']
    ModalAnexar: typeof import('./src/components/ocorrencias/modais/ModalAnexar.vue')['default']
    ModalCobrarSetor: typeof import('./src/components/ocorrencias/modais/ModalCobrarSetor.vue')['default']
    ModalEncaminhar: typeof import('./src/components/ocorrencias/modais/ModalEncaminhar.vue')['default']
    ModalEnviarTemplate: typeof import('./src/components/ocorrencias/modais/ModalEnviarTemplate.vue')['default']
    ModalFinalizar: typeof import('./src/components/ocorrencias/modais/ModalFinalizar.vue')['default']
    ModalNovaLigacao: typeof import('./src/components/ocorrencias/modais/ModalNovaLigacao.vue')['default']
    ModalVideochamada: typeof import('./src/components/ocorrencias/modais/ModalVideochamada.vue')['default']
    ModalVincular: typeof import('./src/components/ocorrencias/modais/ModalVincular.vue')['default']
    NotificacoesPanel: typeof import('./src/components/layout/NotificacoesPanel.vue')['default']
    OcorrenciasBoard: typeof import('./src/components/ocorrencias/OcorrenciasBoard.vue')['default']
    OcorrenciasList: typeof import('./src/components/ocorrencias/OcorrenciasList.vue')['default']
    OperacionalBoard: typeof import('./src/components/gestor/OperacionalBoard.vue')['default']
    PerformanceTab: typeof import('./src/components/gestor/tempo-real/PerformanceTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
